#!/usr/bin/env bash
# upgrade-test.sh — N-1 -> N upgrade test on kind (DEV ONLY).
#
#   hack/quickstart/upgrade-test.sh            # full run
#   hack/quickstart/upgrade-test.sh --apply    # CRDs + helm upgrade only —
#                                              # upgrade.spec.ts calls this
#                                              # with the session held open
#
# Flow (docs/runbooks/upgrade.md): install the PREVIOUS release — the
# published chart and its cosign-signed images — with the same kind +
# Traefik + Postgres + dev Keycloak plumbing as up.sh, seed real state
# (quota row, a Retain workspace holding a file, a stopped workspace, a
# retained-data row, an open portal session), then upgrade to the chart and
# the backend/operator/frontend images built from this working tree and
# assert the state survived. down.sh removes everything.
#
# Environment: the TCDI_QS_* knobs of common.sh plus
#   TCDI_UPGRADE_CHART    OCI ref of the previous chart
#                         (default oci://ghcr.io/tinyorbitvn/charts/tinycdi)
#   TCDI_UPGRADE_VERSION  chart version to start from (default 0.2.0)
#   TCDI_UPGRADE_TAG      git tag the signer certificate names (default v0.2.0)
set -euo pipefail

# shellcheck source-path=SCRIPTDIR source=common.sh
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

UPGRADE_CHART="${TCDI_UPGRADE_CHART:-oci://ghcr.io/tinyorbitvn/charts/tinycdi}"
UPGRADE_VERSION="${TCDI_UPGRADE_VERSION:-0.2.0}"
UPGRADE_TAG="${TCDI_UPGRADE_TAG:-v${UPGRADE_VERSION}}"
# Keyless identity the release workflow signs with (docs: .github/README.md
# "Verifying a release") — exact match, no regexp.
SIGN_ISSUER="https://token.actions.githubusercontent.com"
SIGN_IDENTITY="https://github.com/tinyorbitvn/tinycdi/.github/workflows/release.yml@refs/tags/${UPGRADE_TAG}"

TAG_MARKER="${STATE_DIR}/upgrade-images.tag"
FAIL_MARKER="${STATE_DIR}/upgrade-images.failed"
UPGRADE_VALUES="${STATE_DIR}/values-upgrade.yaml"

# ---- the upgrade itself (runbook order: CRDs -> diff -> helm -> rollouts) ---
apply_upgrade() {
  need kubectl helm sed awk
  log "waiting for the working-tree images (docker build + kind load)"
  for _ in $(seq 1 600); do
    [ -s "$TAG_MARKER" ] && break
    [ -s "$FAIL_MARKER" ] && die "image build failed — see ${STATE_DIR}/logs/build-*.log"
    sleep 2
  done
  [ -s "$TAG_MARKER" ] || die "timed out waiting for the image build"
  local tag; tag="$(cat "$TAG_MARKER")"

  # kindnet enforces NetworkPolicy after the Service NAT — same lookup as
  # up.sh §5 for the apiserver peer, and the node podCIDR holds the Traefik
  # pods whose X-Forwarded-For claims the upgraded backend must trust
  # (docs/runbooks/upgrade.md / chart README: backend.trustedProxies is
  # required behind an ingress or every client shares one rate-limit bucket).
  local api_ip api_port pod_cidr
  api_ip="$(kc -n default get endpointslices -l kubernetes.io/service-name=kubernetes \
    -o jsonpath='{.items[0].endpoints[0].addresses[0]}')"
  api_port="$(kc -n default get endpointslices -l kubernetes.io/service-name=kubernetes \
    -o jsonpath='{.items[0].ports[0].port}')"
  pod_cidr="$(kc get nodes -o jsonpath='{.items[0].spec.podCIDR}')"
  if [ -z "$api_ip" ] || [ -z "$api_port" ] || [ -z "$pod_cidr" ]; then
    die "could not resolve apiserver endpoint or node podCIDR"
  fi

  {
    echo "# generated by upgrade-test.sh - do not edit"
    echo "portalHost: ${PORTAL_HOST}"
    echo "sessionDomain: ${SESSION_DOMAIN}"
    echo "oidc:"
    echo "  issuer: https://${KEYCLOAK_HOST}/realms/tinycdi"
    echo "  postLogoutRedirect: https://${PORTAL_HOST}/signed-out"
    echo "networkPolicy:"
    echo "  apiServerPort: ${api_port}"
    echo "  apiServerPeers:"
    echo "    - ipBlock: {cidr: ${api_ip}/32}"
    echo "images:"
    for c in backend operator frontend; do
      echo "  ${c}:"
      echo "    registry: tcdi-qs.local"
      echo "    repository: tcdi-qs/${c}"
      echo "    tag: \"${tag}\""
    done
    echo "  linuxDesktop:"
    echo "    digest: ${DESKTOP_DIGEST}"
    echo "    builtAt: \"${DESKTOP_BUILT_AT}\""
    echo "  browser:"
    echo "    digest: ${BROWSER_DIGEST}"
    echo "    builtAt: \"${BROWSER_BUILT_AT}\""
    echo "backend:"
    echo "  trustedProxies: [\"${pod_cidr}\"]"
  } >"$UPGRADE_VALUES"

  log "applying the working-tree CRDs first (Helm never upgrades crds/)"
  kc diff -f "$REPO_ROOT/deploy/helm/tinycdi/crds/" 2>&1 | sed 's/^/    /' || true
  kc apply -f "$REPO_ROOT/deploy/helm/tinycdi/crds/"

  log "rendered diff before applying"
  helm template "$RELEASE" "$REPO_ROOT/deploy/helm/tinycdi" -n "$NS_SYSTEM" \
    -f "$QS_DIR/values.yaml" -f "$UPGRADE_VALUES" | kc diff -f - 2>&1 \
    | sed 's/^/    /' || true

  log "helm upgrade to the working-tree chart (images ${tag})"
  helm upgrade "$RELEASE" "$REPO_ROOT/deploy/helm/tinycdi" -n "$NS_SYSTEM" \
    -f "$QS_DIR/values.yaml" -f "$UPGRADE_VALUES" --wait --timeout 10m
  kc -n "$NS_SYSTEM" rollout status deployment/backend deployment/operator --timeout=5m
  kc -n "$NS_SYSTEM" rollout status deployment/frontend --timeout=5m
  log "upgrade applied"
}

# ---- helpers for the main flow ------------------------------------------------

# chart_field <component> <key>: read images.<component>.<key> out of the
# packaged chart's values (digests are stamped in at release time).
chart_field() {
  awk -v comp="$1" -v key="$2" '
    $0 == "images:" {ins=1; inc=0; next}
    ins && /^  [a-zA-Z]/ {inc = ($0 == "  "comp":"); next}
    ins && inc && $1 == key":" {v=$2; gsub(/"/, "", v); print v; exit}
    ins && /^[a-zA-Z]/ {ins=0}
  ' "$CHART_VALS"
}

# build_and_load <tag>: the same image build + kind load as up.sh, run in the
# background while the previous release is installed. Writes TAG_MARKER on
# success; the caller turns any failure into FAIL_MARKER.
build_and_load() {
  local tag="$1" c pids=() pid
  for c in backend operator frontend; do
    (cd "$REPO_ROOT" && docker build -q -f "build/${c}/Dockerfile" \
      -t "${LOCAL_IMAGE_PREFIX}/${c}:${tag}" . >"$STATE_DIR/logs/build-${c}.log" 2>&1) &
    pids+=($!)
  done
  for pid in "${pids[@]}"; do
    wait "$pid" || { tail -n 40 "$STATE_DIR"/logs/build-*.log >&2; return 1; }
  done
  # The cluster may not exist yet — up.sh is creating it in parallel.
  for _ in $(seq 1 300); do
    kind get clusters 2>/dev/null | grep -qx "$CLUSTER" && break
    sleep 2
  done
  kind get clusters 2>/dev/null | grep -qx "$CLUSTER" || return 1
  kind load docker-image --name "$CLUSTER" \
    "${LOCAL_IMAGE_PREFIX}/backend:${tag}" \
    "${LOCAL_IMAGE_PREFIX}/operator:${tag}" \
    "${LOCAL_IMAGE_PREFIX}/frontend:${tag}" \
    >"$STATE_DIR/logs/kind-load.log" 2>&1 || return 1
  echo "$tag" >"$TAG_MARKER"
  # The upgraded templates pin the current runtime train; keep pulling it so
  # post-upgrade workspace starts do not wait on ~1 GB pulls (best effort).
  docker exec "${CLUSTER}-control-plane" crictl pull \
    "ghcr.io/tinyorbitvn/tinycdi-browser@${BROWSER_DIGEST}" >/dev/null 2>&1 &
  docker exec "${CLUSTER}-control-plane" crictl pull \
    "ghcr.io/tinyorbitvn/tinycdi-linux-desktop@${DESKTOP_DIGEST}" >/dev/null 2>&1 &
  return 0
}

# dump_cluster_diag: capture everything that explains a pre-upgrade
# failure — per-pod restart counts, events, EndpointSlices and the logs of
# every component the seeding phase drives — into a timestamped dir under
# ${STATE_DIR}/logs so the CI artifact shows WHY the stack was unstable,
# not only the playwright error. Best effort: never fails the caller.
dump_cluster_diag() {
  local d ns dep
  d="${STATE_DIR}/logs/diag-$(date +%Y%m%d-%H%M%S)"
  mkdir -p "$d" || return 0
  kc get pods -A -o wide >"$d/pods.txt" 2>&1 || true
  # pods.json carries containerStatuses[].restartCount and the Ready
  # conditions — the answers to "did something restart" and "what was
  # ready on paper while the edge was dead".
  kc get pods -A -o json >"$d/pods.json" 2>&1 || true
  kc get events -A --sort-by=.lastTimestamp >"$d/events.txt" 2>&1 || true
  kc get endpointslices -A -o yaml >"$d/endpointslices.yaml" 2>&1 || true
  kc get workspaces,workspacetemplates -A -o wide >"$d/workspaces.txt" 2>&1 || true
  kc get nodes -o wide >"$d/nodes.txt" 2>&1 || true
  kc describe nodes >"$d/nodes-describe.txt" 2>&1 || true
  for ns_dep in \
    "${NS_SYSTEM}/backend" "${NS_SYSTEM}/operator" "${NS_SYSTEM}/frontend" \
    "${NS_INGRESS}/traefik" "${NS_DEPS}/keycloak" "kube-system/coredns"; do
    ns="${ns_dep%/*}"; dep="${ns_dep#*/}"
    kc -n "$ns" logs "deployment/$dep" --all-containers --tail=500 \
      >"$d/log-${dep}.txt" 2>&1 || true
    kc -n "$ns" logs "deployment/$dep" --all-containers --previous --tail=200 \
      >"$d/log-${dep}-previous.txt" 2>&1 || true
  done
  kc -n "$NS_DEPS" logs statefulset/postgres --tail=300 \
    >"$d/log-postgres.txt" 2>&1 || true
  # The node-side services are the other half of the story: the
  # containerd/kubelet restart window lives in the node's journal.
  docker exec "${CLUSTER}-control-plane" \
    journalctl -u kubelet -u containerd --since "-15 min" --no-pager \
    >"$d/node-journal.txt" 2>&1 || true
  warn "cluster diagnostics dumped to $d"
}

on_error() {
  local rc=$?
  warn "upgrade-test.sh failed (exit $rc). Logs: ${STATE_DIR}/logs"
  if [ -s "$KUBECONFIG" ]; then
    warn "pods not ready:"
    kc get pods -A --no-headers 2>/dev/null | grep -Ev 'Running|Completed' >&2 || true
    dump_cluster_diag
  fi
  warn "tear down with: hack/quickstart/down.sh"
  exit "$rc"
}

SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"

if [ "${1:-}" = "--apply" ]; then
  apply_upgrade
  exit 0
fi
if [ "${1:-}" = "--build" ]; then
  # internal: the background leg (kept out of the foreground script so its
  # docker-build children die with it if the run is aborted)
  build_and_load "$2"
  exit $?
fi
if [ "${1:-}" = "--collect-diag" ]; then
  # internal: CI calls this on job failure (covers a SIGTERM-killed run,
  # where the ERR trap never fires)
  dump_cluster_diag
  exit 0
fi

trap on_error ERR

need docker kind kubectl helm cosign curl sed awk sha256sum npm npx
docker info >/dev/null 2>&1 || die "cannot talk to the Docker daemon"
umask 077
mkdir -p "$STATE_DIR/logs"

# ---- 1. fetch and verify the previous release --------------------------------
log "pulling ${UPGRADE_CHART} version ${UPGRADE_VERSION}"
mkdir -p "$STATE_DIR/chart"
pull_out="$(helm pull "$UPGRADE_CHART" --version "$UPGRADE_VERSION" \
  --destination "$STATE_DIR/chart" 2>&1)" || { printf '%s\n' "$pull_out" >&2; die "helm pull failed"; }
CHART_TGZ="$(find "$STATE_DIR/chart" -maxdepth 1 -name '*.tgz' | head -1)"
if [ -z "$CHART_TGZ" ] || [ ! -s "$CHART_TGZ" ]; then
  die "no chart tarball under $STATE_DIR/chart"
fi
chart_digest="$(printf '%s\n' "$pull_out" | grep -oE 'sha256:[0-9a-f]{64}' | head -1)"
CHART_VALS="$STATE_DIR/chart-values-${UPGRADE_VERSION}.yaml"
helm show values "$CHART_TGZ" >"$CHART_VALS"

log "verifying release signatures (cosign, identity ...@${UPGRADE_TAG})"
case "$UPGRADE_CHART" in
  oci://*)
    [ -n "$chart_digest" ] || die "helm pull did not report a chart digest"
    cosign verify "${UPGRADE_CHART#oci://}@${chart_digest}" \
      --certificate-oidc-issuer "$SIGN_ISSUER" \
      --certificate-identity "$SIGN_IDENTITY" >"$STATE_DIR/logs/cosign-chart.log" 2>&1 \
      || { cat "$STATE_DIR/logs/cosign-chart.log" >&2; die "chart signature verification failed"; }
    ;;
esac
REGISTRY="$(awk '/^global:/{g=1;next} g&&/^  imageRegistry:/{print $2;exit} g&&/^[a-z]/{g=0}' "$CHART_VALS")"
REGISTRY="${REGISTRY:-ghcr.io}"
for c in backend operator frontend; do
  repo="$(chart_field "$c" repository)"
  dig="$(chart_field "$c" digest)"
  if [ -z "$repo" ] || [ -z "$dig" ]; then
    die "images.$c not digest-pinned in the $UPGRADE_VERSION chart"
  fi
  cosign verify "${REGISTRY}/${repo}@${dig}" \
    --certificate-oidc-issuer "$SIGN_ISSUER" \
    --certificate-identity "$SIGN_IDENTITY" >"$STATE_DIR/logs/cosign-${c}.log" 2>&1 \
    || { cat "$STATE_DIR/logs/cosign-${c}.log" >&2; die "signature verification failed for images.$c"; }
  log "verified ${c}@${dig:0:24}…"
done
# The previous release's own runtime pins, so the seeded workspaces run what
# a real ${UPGRADE_TAG} install would (its template snapshots survive the
# upgrade and keep pulling these).
RT_DESKTOP_DIGEST="$(chart_field linuxDesktop digest)"
RT_BROWSER_DIGEST="$(chart_field browser digest)"
if [ -z "$RT_DESKTOP_DIGEST" ] || [ -z "$RT_BROWSER_DIGEST" ]; then
  die "runtime images not digest-pinned in the $UPGRADE_VERSION chart"
fi

# ---- 2. build the working-tree images in the background ----------------------
UPG_TAG="upg-$(date +%s)"
rm -f "$TAG_MARKER" "$FAIL_MARKER"
"$SELF" --build "$UPG_TAG" >"$STATE_DIR/logs/build-load.log" 2>&1 \
  || touch "$FAIL_MARKER" &
BUILD_PID=$!
trap 'kill "$BUILD_PID" 2>/dev/null || true' EXIT

# ---- 3. kind + deps + the previous release (up.sh does the same plumbing) ----
# The TCDI_QS_* overrides are scoped to the up.sh call only — exported, they
# would leak into the spec's environment and the --apply leg would pin the
# old release's runtime digests in the upgrade values instead of this tree's.
TCDI_QS_IMAGES=published \
TCDI_QS_CHART="$CHART_TGZ" \
TCDI_QS_VALUES="$QS_DIR/values-v0.2.yaml" \
TCDI_QS_BROWSER_DIGEST="$RT_BROWSER_DIGEST" \
TCDI_QS_DESKTOP_DIGEST="$RT_DESKTOP_DIGEST" \
TCDI_QS_BROWSER_BUILT_AT="" \
TCDI_QS_DESKTOP_BUILT_AT="" \
"$QS_DIR/up.sh"

# ---- 3b. give the kind node AppArmor (the previous release requires it) ------
# v0.2.0 unconditionally sets appArmorProfile: RuntimeDefault on workspace
# pods — the runtime.appArmor.requireRuntimeDefault opt-out is a v0.3 knob.
# A real node satisfies that; a kind node can use the host kernel's AppArmor:
# apparmor_parser in the node + securityfs mounted, then containerd AND
# kubelet restarted — both cache "apparmor unsupported" at startup
# (containerd's sync.Once HostSupports probe wants securityfs + parser +
# kernel param; kubelet does its own one-time check). Without an
# AppArmor-capable host kernel v0.2.0 workspaces simply cannot run — fail
# loudly instead of timing out on AppArmor-rejected pods.
log "enabling AppArmor inside the kind node (the ${UPGRADE_TAG} runtime requires RuntimeDefault)"
NODE="${CLUSTER}-control-plane"
if [ "$(docker exec "$NODE" cat /sys/module/apparmor/parameters/enabled 2>/dev/null || true)" != "Y" ]; then
  die "host kernel has no AppArmor — ${UPGRADE_TAG} workspace pods require RuntimeDefault AppArmor (the opt-out landed in v0.3); run on a host with AppArmor enabled"
fi
docker exec "$NODE" apt-get update -qq >/dev/null
docker exec "$NODE" apt-get install -y -qq apparmor >/dev/null
docker exec "$NODE" mount -t securityfs securityfs /sys/kernel/security 2>/dev/null || true
docker exec "$NODE" systemctl restart containerd kubelet
# The restarts briefly unready the apiserver (static pods respawn).
for _ in $(seq 1 90); do
  kc get --raw=/readyz >/dev/null 2>&1 && break
  sleep 2
done
kc get --raw=/readyz >/dev/null 2>&1 || die "apiserver did not recover after the containerd/kubelet restart"
# Probe exactly what the released runtime needs: a pod whose container
# carries appArmorProfile: RuntimeDefault must be schedulable. A rejected
# pod sits at reason=AppArmor forever — surface it in seconds instead of
# letting a workspace hit its ten-minute readiness timeout.
kc -n default delete pod upgrade-aa-probe --ignore-not-found --wait=false >/dev/null 2>&1 || true
cat <<'EOF' | kc -n default apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: upgrade-aa-probe
spec:
  containers:
    - name: c
      image: busybox:stable
      command: ["sleep", "30"]
      securityContext:
        appArmorProfile:
          type: RuntimeDefault
EOF
aa_state=""
for _ in $(seq 1 90); do
  aa_state="$(kc -n default get pod upgrade-aa-probe \
    -o jsonpath='{.status.phase}:{.status.containerStatuses[0].state.waiting.reason}' 2>/dev/null || true)"
  case "$aa_state" in
    Running:|Succeeded:|*:AppArmor) break ;;
  esac
  sleep 2
done
case "$aa_state" in
  Running:|Succeeded:) ;;
  *) die "RuntimeDefault AppArmor is still not supported on the kind node (probe pod: ${aa_state:-unknown}) — ${UPGRADE_TAG} workspaces cannot run here" ;;
esac
kc -n default delete pod upgrade-aa-probe --wait=false >/dev/null 2>&1 || true

# ---- 3c. seeding gate: the stack must be routable, not just Ready -----------
# The containerd+kubelet restart above takes the node agent down for however
# long systemd needs; on a loaded runner that can cross the ~40 s
# node-monitor grace, the node then goes Unknown and EVERY EndpointSlice
# drains — Traefik's own NodePort endpoints included — so the portal
# refuses connections (and returns 5xx while partial endpoints come back)
# for the next ~30-90 s. Pod Ready is not the same as the stack being
# served end to end, so wait for the condition the spec actually drives:
# node Ready, every workload pod Ready, a ready endpoint behind each
# edge-facing Service, the seeded template objects present, and GET / plus
# the API answering through the ingress — a few consecutive good rounds,
# because one good reply can catch the edge mid-flap. (FLAKE3)
edge_code() { # edge_code <host> <path>: HTTP status through Traefik on loopback
  curl -sS --max-time 10 --cacert "${STATE_DIR}/tls/local-ca.crt" \
    --resolve "$1:443:127.0.0.1" -o /dev/null -w '%{http_code}' \
    "https://$1$2" 2>/dev/null || true
}
ep_ready() { # ep_ready <ns> <service>: an EndpointSlice has a ready endpoint
  kc -n "$1" get endpointslices -l "kubernetes.io/service-name=$2" \
    -o jsonpath='{.items[*].endpoints[?(@.conditions.ready==true)].addresses[*]}' \
    2>/dev/null | grep -q .
}
all_pods_ready() { # every pod in the namespaces this test drives is Ready
  local ns bad
  for ns in "$NS_SYSTEM" "$NS_TENANT" tinycdi-tenant-noquota "$NS_DEPS" "$NS_INGRESS"; do
    bad="$(kc -n "$ns" get pods \
      -o jsonpath='{range .items[*]}{.status.conditions[?(@.type=="Ready")].status}{"\n"}{end}' \
      2>/dev/null | grep -cv '^True$' || true)"
    [ "$bad" -gt 0 ] && return 1
  done
  return 0
}

log "waiting for the ${UPGRADE_TAG} stack to be routable end to end (seeding gate)"
stable=0
for _ in $(seq 1 90); do
  ok=1
  kc get nodes -o jsonpath='{.items[*].status.conditions[?(@.type=="Ready")].status}' \
    2>/dev/null | grep -qw True || ok=0
  all_pods_ready || ok=0
  ep_ready "$NS_SYSTEM" backend || ok=0
  ep_ready "$NS_SYSTEM" frontend || ok=0
  ep_ready "$NS_DEPS" keycloak || ok=0
  ep_ready "$NS_DEPS" postgres || ok=0
  ep_ready "$NS_INGRESS" traefik || ok=0
  [ "$(kc -n "$NS_TENANT" get workspacetemplates --no-headers 2>/dev/null | wc -l)" -ge 2 ] || ok=0
  [ "$(edge_code "$PORTAL_HOST" /)" = 200 ] || ok=0
  # 401 is the win here: it proves the request crossed Traefik and the
  # backend answered — the authed catalog check itself is in the spec.
  [ "$(edge_code "$PORTAL_HOST" /v1/templates)" = 401 ] || ok=0
  [ "$(edge_code "$KEYCLOAK_HOST" /realms/tinycdi/.well-known/openid-configuration)" = 200 ] || ok=0
  if [ "$ok" = 1 ]; then stable=$((stable + 1)); else stable=0; fi
  [ "$stable" -ge 3 ] && break
  sleep 2
done
if [ "$stable" -lt 3 ]; then
  warn "the ${UPGRADE_TAG} stack never became routable"
  dump_cluster_diag
  die "seeding gate timed out: stack not routable end to end"
fi
log "stack is routable end to end"

# ---- 4. seed + upgrade + verify (hack/quickstart/smoke/upgrade.spec.ts) ------
# The spec holds a live desktop session open while it runs this script's
# --apply leg, so the same browser context proves the stream reconnects
# inside its lease (no new launch ticket).
set -a
# shellcheck source=/dev/null # written by up.sh: portal URL, users, KUBECONFIG
. "$STATE_DIR/env"
set +a
export TCDI_UPGRADE_STATE_DIR="$STATE_DIR"
export TCDI_UPGRADE_APPLY="$SELF"
(cd "$QS_DIR/smoke" && npm ci --no-audit --no-fund \
  && npx playwright test --config playwright.upgrade.config.ts)
