#!/usr/bin/env bash
# check-trivyignore.sh — enforce the expiring-exceptions policy on .trivyignore.
#
# SEC-44: .trivyignore is an exceptions file, not a blanket pass. Every
# finding-ID entry must be immediately preceded by a comment block
# declaring, at column 0, in any order:
#   # reason:   <why the finding is accepted>          (non-empty)
#   # approver: <github handle of the approver>        (non-empty)
#   # expires:  YYYY-MM-DD  — in the future, at most 30 days ahead
#
# Expiry is enforced AT SCAN TIME, not just here: with --out the script
# writes an effective ignorefile containing only the unexpired entries,
# each suffixed with trivy's native `exp:YYYY-MM-DD`. The scan jobs pass
# that file via --ignorefile, so a stale/expired source entry can never
# suppress a finding even if this checker's CI leg was bypassed.
#
# Usage: check-trivyignore.sh [--out EFFECTIVE-FILE] [path-to-.trivyignore]
# Exit 0 when the file is absent, empty, or fully compliant; 1 otherwise.
set -euo pipefail

OUT=""
if [ "${1:-}" = "--out" ]; then
  OUT="${2:?--out requires a path}"
  shift 2
fi
FILE="${1:-.trivyignore}"

if [ -n "$OUT" ]; then
  {
    echo "# effective ignorefile generated by check-trivyignore.sh — do not edit."
    echo "# expired/malformed entries from $FILE are dropped; each entry carries"
    echo "# trivy's native exp: so suppression lapses at the stated date."
  } > "$OUT"
fi

[ -f "$FILE" ] || exit 0

now="$(date +%s)"
max="$(date -d "+30 days" +%s)"
fail=0
trim() { local v="$1"; v="${v#"${v%%[![:space:]]*}"}"; printf '%s' "${v%"${v##*[![:space:]]}"}"; }

reason="" approver="" expires=""
lineno=0
while IFS= read -r raw || [ -n "$raw" ]; do
  lineno=$((lineno + 1))
  line="${raw%$'\r'}"  # tolerate CRLF; the emitted file is LF
  case "$line" in
    '# reason:'*)   reason="$(trim "${line#'# reason:'}")" ;;
    '# approver:'*) approver="$(trim "${line#'# approver:'}")" ;;
    '# expires:'*)  expires="$(trim "${line#'# expires:'}")" ;;
    '#'*|'') ;;  # other comments and blank lines are free-form
    *)
      # One finding ID per line; an inline `exp:` suffix is allowed but must
      # match the comment's expiry so the two can never disagree.
      id="" inline_exp=""
      if [[ "$line" =~ ^[A-Za-z0-9][A-Za-z0-9_.-]*([[:space:]]+exp:([0-9]{4}-[0-9]{2}-[0-9]{2}))?$ ]]; then
        id="${line%% *}"
        inline_exp="${BASH_REMATCH[2]:-}"
      fi
      if [ -z "$id" ]; then
        echo "::error file=$FILE,line=$lineno::entry '$line' is not a single finding ID (optional ' exp:YYYY-MM-DD' suffix allowed)"
        fail=1
      elif [ -z "$reason" ] || [ -z "$approver" ]; then
        echo "::error file=$FILE,line=$lineno::entry '$id' lacks a non-empty reason/approver comment"
        fail=1
      elif [[ ! "$expires" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]] \
        || ! exp_epoch="$(date -d "$expires" +%s 2>/dev/null)"; then
        echo "::error file=$FILE,line=$lineno::entry '$id' has unparseable expires '$expires' (want YYYY-MM-DD)"
        fail=1
      elif [ "$exp_epoch" -le "$now" ]; then
        echo "::error file=$FILE,line=$lineno::entry '$id' exception expired on $expires"
        fail=1
      elif [ "$exp_epoch" -gt "$max" ]; then
        echo "::error file=$FILE,line=$lineno::entry '$id' expires '$expires' is beyond the 30-day horizon"
        fail=1
      elif [ -n "$inline_exp" ] && [ "$inline_exp" != "$expires" ]; then
        echo "::error file=$FILE,line=$lineno::entry '$id' inline exp '$inline_exp' disagrees with '# expires: $expires'"
        fail=1
      elif [ -n "$OUT" ]; then
        printf '%s exp:%s\n' "$id" "$expires" >> "$OUT"
      fi
      reason="" approver="" expires=""
      ;;
  esac
done < "$FILE"
exit "$fail"
